apiVersion: apps/v1
kind: Deployment
metadata:
  name: oracle12c
  namespace: default
  labels:
    app: client
    version: 12.2.0.1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
      version: 12.2.0.1
  template:
    metadata:
      name: oracle12c
      labels:
        app: client
        version: 12.2.0.1
    spec:
      securityContext:
        fsGroup: 54321
      containers:
        - name: oracle12c
          image: 'phx.ocir.io/orasenatdpltintegration01/gomrepo/ol7_122:latest'
          ports:
            - name: listener
              containerPort: 1521
              hostPort: 1521
          env:
            - name: PRIMARY_HOST 
              value: "10.1.0.106"
            - name: PRIMARY_DB_PORT 
              value: "1521"
            - name: PRIMARY_DB_SVC 
              value: "DB122_PHX.sub04050841080.gomvcn.oraclevcn.com"
            - name: STANDBY_HOST 
              value: "10.1.0.236"
            - name: STANDBY_DB_PORT 
              value: "1521"
            - name: STANDBY_DB_SVC 
              value: "DB122_phx3dr.sub04050841080.gomvcn.oraclevcn.com"
            - name: SYS_PASSWORD 
              value: "MAnager1234##"
      imagePullSecrets:
        - name: ocirsecret
---
apiVersion: v1
kind: Service
metadata:
  name: oracle12c
  namespace: default
  labels:
    app: client
    version: 12.2.0.1
spec:
  selector:
    app: client
    version: 12.2.0.1
  type: NodePort
  ports:
  - name: listener
    protocol: TCP
    port: 1521
    targetPort: 1521

